config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users, only: [:index, :show] do
      post '/prohibition', to: 'users#update'
      delete '/prohibition', to: 'users#destroy'
    end
  end

  get 'weekly_ranking', to: 'weekly_ranking#index'
  get 'all_time_ranking', to: 'all_time_ranking#index'

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get 'sign_in', :to => 'users/sessions#new'
    get 'sign_out', :to => 'users/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end


  resources :users do
    member do
      get 'profile/show', to: 'users/profile#show'
      get 'profile/edit', to: 'users/profile#edit'
      patch 'profile/update', to: 'users/profile#update'
    end

    member do
      get :followings, :follower
    end
  end

  resources :follow_relationships, only: [:create, :destroy]

  root to: 'home#index'
end

app/views/shared/_create_new_post_btn.html.erb
<div class='nav justify-content-end' style="position:fixed; bottom:25px; right:25px; z-index: 999;">
  <%= link_to new_post_url, class: 'btn btn-primary rounded-circle', style: 'width: 80px; height: 80px; display: flex; justify-content: center; align-items: center;' do %>
    <i class="fas fa-plus"></i>
  <% end %>
</div>

app/views/shared/_errors_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class='card text-left'>
    <div class="card-footer text-muted">
      <% if signed_in? && current_user.admin? %>
        <div>
          <%= link_to '管理人ページ', admin_users_path, class: 'text-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Home', root_url, class: 'navbar-brand' %>
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li class="nav-item"><%= link_to current_user.name,
              profile_show_user_path(current_user), class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'ログアウト', sign_out_path, class: 'nav-link' %></li>
      <% else %>
        <li class="nav-item"><%= link_to 'かんたんログイン', users_guest_sign_in_path, method: :post, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'サインアップ', new_user_registration_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/shared/_ranking_link_bar.html.erb
<div class="nav justify-content-end my-3" id="ranking_link_bar">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to '新着投稿', posts_path, class: 'nav-link text-secondary'  %>
    </li>
    <li class="nav-item">
      <%= link_to '総合いいね', all_time_ranking_path, class: 'nav-link text-secondary' %>
    </li>
    <li class="nav-item">
      <%= link_to '週間いいね', weekly_ranking_path, class: 'nav-link text-secondary' %>
    </li>
  </ul>
</div>

app/views/shared/_user_profile_bar.html.erb
<div class="card-footer bg-linght">
<div>
  <%= link_to  profile_show_user_path(post.user) do %>
    <div class="d-inline-block">
    <% if post.user.avatar.attached? %>
      <%= image_tag post.user.avatar.variant(resize:"240x240").processed, class: 'user-avatar-trim-to-circle',
              style: "width: 25px; height: 25px;", id: 'user_avatar' %>
    <% end %>
    </div>
    <div class="d-inline-block ml-3 text-secondary">
      <%= post.user.name %>
    </div>
  <% end %>
</div>
</div>