config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users, only: [:index, :show] do
      post '/prohibition', to: 'users#update'
      delete '/prohibition', to: 'users#destroy'
    end
  end

  get 'weekly_ranking', to: 'weekly_ranking#index'
  get 'all_time_ranking', to: 'all_time_ranking#index'

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get 'sign_in', :to => 'users/sessions#new'
    get 'sign_out', :to => 'users/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end


  resources :users do
    member do
      get 'profile/show', to: 'users/profile#show'
      get 'profile/edit', to: 'users/profile#edit'
      patch 'profile/update', to: 'users/profile#update'
    end

    member do
      get :followings, :follower
    end
  end

  resources :follow_relationships, only: [:create, :destroy]

  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @posts = Post.all.order(created_at: :desc).limit(4)

    to  = Time.current.at_end_of_day
    from    = (to - 6.day).at_beginning_of_day
    posts_weekly = Post.where(created_at: from...to)
    posts_likes_weekly_desc = posts_weekly.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
    @posts_likes_weekly = posts_likes_weekly_desc.first(4)

    posts_likes_all_time_desc = Post.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
    @posts_likes_all_time = posts_likes_all_time_desc.first(4)


    agent = Mechanize.new
    #ローソン
    from_lawson = agent.get("https://www.lawson.co.jp/recommend/original/dessert/")
    @lawson_new_items = from_lawson.search('article#dessert li').first(4)

    #ファミマ
    from_famima = agent.get("https://www.family.co.jp/goods/dessert.html")
    @famima_new_items = from_famima.search('div.ly-list-goods .ly-mod-layout-clm a').first(4)

    if user_signed_in?
      @followings_new_posts = Post.where(user_id: current_user.following_ids).order(created_at: :desc).limit(4)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!--コンビニ新着アイテム-->
<div style="margin: 0 auto 80px;">
  <h2>New Sweets</h2>
</div>

<div class="my-5">
  <!--ローソン-->
  <div class="mt-5">
    <h3>ローソン新作</h3>
    <hr size="20" noshad>
    <div class="card-deck">
      <% @lawson_new_items.each do |item| %>
        <div class="card">
          <%= link_to 'https://www.lawson.co.jp/' + item.search('a').attribute('href'), target: '_blank' do %>
            <img src="https://www.lawson.co.jp/<%= item.search('img').attribute('src') %>"
                  style="width: 100%", class="adjust_image_size" />
          <% end %>

          <div class="card-body">
            <div class="my-1">
              <p class="card-text">
                <small class="text-muted"><%= item.search('img').attribute('alt') %></small>
                <br>
                <small class="text-muted"><%= item.search('p.price').inner_text %></small>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <!--end-->

  <!--ファミマの新着アイテム-->
  <div class="mt-5">
    <h3>ファミマ新作</h3>
    <hr size="20" noshad>
    <div class="card-deck">
      <% @famima_new_items.each do |item| %>
        <div class="card">

          <%= link_to item[:href], target: '_blank' do %>
            <img src="https://www.family.co.jp/<%= item.search('img').attribute('src') %>"
                  style="width: 100%", class="adjust_image_size" />
          <% end %>

          <div class="card-body">
            <div class="my-1">
              <p class="card-text">
                <small class="text-muted"><%= item.search('p.ly-mod-infoset4-name').inner_text %></small>
                <br>
                <small class="text-muted"><%= item.search('p.ly-mod-infoset4-price').inner_text %></small>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <!--end-->
</div>
<!--end-->


<div style="margin: 120px auto 80px;">
  <h2>みんなのおすすめ</h2>
</div>

<!-- フォロー新着 -->
<% if user_signed_in? %>
  <div id="followings_new_posts">
    <h3>フォロー新着</h3>
    <hr size="20" noshad>
    <div class="card-deck">
      <% @followings_new_posts.each do |post| %>
        <div style="display: flex; flex-wrap: wrap">
          <div class="card" style="width: 12rem;">
            <% if post.image.attached? %>
              <%= link_to post_path(post), target: "_blank" do %>
                <%= image_tag post.image.variant(gravity: :center, resize:"480x480^", crop:"480x480+0+0").processed,
                        class: 'card-img-top', style: 'width: 100%; height: auto', id: 'following_new_post' %>
              <% end %>
            <% end %>

            <%= render partial: 'shared/user_profile_bar', locals: {post: post} %>

            <div class="card-body">
              <div id="likes_buttons_<%= post.id %>">
                <%= render partial: 'likes/like', locals: {post: post} %>
              </div>
              <p class="card-text"><small class="text-muted">投稿日時: <%= post.created_at.strftime("%Y-%m-%d %H:%M") %></small></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<!--end-->


<!-- 新着投稿 -->
<div id="new_posts" class="mt-5">
  <h3>新着投稿</h3>
  <hr size="20" noshad>
  <div class="card-deck">
    <% @posts.each do |post| %>
      <div class="card">
        <% if post.image.attached? %>
          <%= link_to post_path(post), target: "_blank" do %>
            <%= image_tag post.image.variant(gravity: :center, resize:"480x480^", crop:"480x480+0+0").processed,
                    class: 'card-img-top', style: 'width: 100%; height: auto', alt: '' %>
          <% end %>
        <% end %>

        <%= render partial: 'shared/user_profile_bar', locals: {post: post} %>

        <div class="card-body">
          <div id="likes_buttons_<%= post.id %>">
            <%= render partial: 'likes/like', locals: {post: post} %>
          </div>
          <p class="card-text"><small class="text-muted">投稿日時: <%= post.created_at.strftime("%Y-%m-%d %H:%M") %></small></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="nav justify-content-end mt-3">
    <%= link_to 'もっと見る', posts_path, class: 'text-secondary' %>
  </div>
</div>
<!--end-->


<!--週間いいね順-->
<div class="mt-5">
  <h3>週間ランキング</h3>
  <hr size="20" noshad>
  <div class="card-deck">
    <% @posts_likes_weekly.each do |post| %>
      <div class="card">
        <% if post.image.attached? %>
          <%= link_to post_path(post), target: "_blank" do %>
            <%= image_tag post.image.variant(gravity: :center, resize:"480x480^", crop:"480x480+0+0").processed,
                    class: 'card-img-top', style: 'width: 100%; height: auto', alt: '' %>
          <% end %>
        <% end %>

        <%= render partial: 'shared/user_profile_bar', locals: {post: post} %>

        <div class="card-body">
          <div class="nav justify-content-end mt-1 mr-1">
            <p><small class="text-muted"><%= post.liked_users.count %> likes</small></p>
          </div>
          <p class="card-text"><small class="text-muted">投稿日時: <%= post.created_at.strftime("%Y-%m-%d %H:%M") %></small></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="nav justify-content-end mt-3">
    <%= link_to 'もっと見る', weekly_ranking_path, class: 'text-secondary' %>
  </div>
</div>
<!--end-->


<!--総合いいね順-->
<div class="mt-5">
  <h3>総合ランキング</h3>
  <hr size="20" noshad>
  <div class="card-deck">
    <% @posts_likes_all_time.each do |post| %>
      <div class="card">
        <% if post.image.attached? %>
          <%= link_to post_path(post), target: "_blank" do %>
            <%= image_tag post.image.variant(gravity: :center, resize:"480x480^", crop:"480x480+0+0").processed,
                    class: 'card-img-top', style: 'width: 100%; height: auto', alt: '' %>
          <% end %>
        <% end %>

        <%= render partial: 'shared/user_profile_bar', locals: {post: post} %>

        <div class="card-body">
          <div class="nav justify-content-end mt-1 mr-1">
            <p><small class="text-muted"><%= post.liked_users.count %> likes</small></p>
          </div>
          <p class="card-text"><small class="text-muted">投稿日時: <%= post.created_at.strftime("%Y-%m-%d %H:%M") %></small></p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="nav justify-content-end mt-3">
    <%= link_to 'もっと見る', all_time_ranking_path, class: 'text-secondary' %>
  </div>
</div>
<!--end-->


<%= render partial: 'shared/create_new_post_btn' %>