config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users, only: [:index, :show] do
      post '/prohibition', to: 'users#update'
      delete '/prohibition', to: 'users#destroy'
    end
  end

  get 'weekly_ranking', to: 'weekly_ranking#index'
  get 'all_time_ranking', to: 'all_time_ranking#index'

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    get 'sign_in', :to => 'users/sessions#new'
    get 'sign_out', :to => 'users/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end


  resources :users do
    member do
      get 'profile/show', to: 'users/profile#show'
      get 'profile/edit', to: 'users/profile#edit'
      patch 'profile/update', to: 'users/profile#update'
    end

    member do
      get :followings, :follower
    end
  end

  resources :follow_relationships, only: [:create, :destroy]

  root to: 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  require 'faker'

  before_create :set_default_user_avatar

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, :through => :likes, :source => :post
  has_many :comments, dependent: :destroy

  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'FollowRelationship', dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'FollowRelationship', dependent: :destroy
  has_many :follower, through: :follower_relationships


  def following?(other_user)
    self.followings.include?(other_user)
  end

  def follow(other_user)
    self.following_relationships.create(following_id: other_user.id)
  end

  def unfollow(other_user)
    self.following_relationships.find_by(following_id: other_user.id).destroy
  end

  def self.guest
    int = rand(100) + 1
    User.create!(
      email: "guest#{int}@example.com",
      password: 'password',
      introduction: Faker::Movies::HarryPotter.quote
    )
  end

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def set_default_user_avatar
    if !self.avatar.attached?
      self.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'icon_user.jpg')),
                              filename: 'default-user-avatar.jpg', content_type: 'image/jpg')
    end
  end
end

app/controllers/admin/user_controller.rb
class Admin::UserController < ApplicationController
  before_action :authenticate_user!
  before_action :user_admin?

  def index
    @users = User.page(params[:page]).per(50).order(created_at: :desc)
  end

  def update
    user = User.find(params[:id])
    if user.update(prohibition: true)
      redirect_back(fallback_location: admin_users_path)
    end
  end

  def destroy
    user = User.find(params[:id])
    if user.update(prohibition: false)
      redirect_back(fallback_location: admin_users_path)
    end
  end

  private
    def user_admin?
      redirect_to root_url unless current_user.admin?
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :user_admin?

  def index
    @users = User.page(params[:page]).per(50).order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(50).order(created_at: :desc)
  end

  def update
    user = User.find(params[:user_id])
    if user.update(prohibition: true)
      redirect_back(fallback_location: admin_users_path)
    end
  end

  def destroy
    user = User.find(params[:user_id])
    if user.update(prohibition: false)
      redirect_back(fallback_location: admin_users_path)
    end
  end

  private
    def user_admin?
      redirect_to root_url unless current_user.admin?
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/profile_controller.rb
class Users::ProfileController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(12).order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update!(user_profile_params)
      redirect_to profile_show_user_path(@user), notice: 'プロフィールを更新しました'
    else
      render profile_edit_user_path(@user)
    end
  end

  private
    def user_profile_params
      params.require(:user).permit(:avatar, :name, :introduction)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:email])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(resource)
    profile_show_user_path(@user)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: '自動生成でログインしました。デフォルトのパスワードは[ password ]です。今後もこのアカウントを利用される場合、ユーザーページ＞プロフィール編集からメールアドレス、パスワード等の確認をしてください。'
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def followings
    @user = User.find(params[:id])
    @users = @user.followings.page(params[:page]).per(5)
  end

  def follower
    @user = User.find(params[:id])
    @users = @user.follower.page(params[:page]).per(5)
  end

end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/users/profile_helper.rb
module Users::ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profile/_follow_btn.html.erb
<% if current_user != user %>
  <div>
    <% if current_user.following?(user) %>
      <%= form_with(model: current_user.following_relationships.find_by(following_id: user.id), method: :delete, local: true) do |f| %>
        <%= f.hidden_field :following_id %>
        <%= f.submit 'フォロー解除', class: 'btn btn-outline-danger' %>
      <% end %>
    <% else %>
      <%= form_with(model: current_user.following_relationships.build, local: true) do |f| %>
        <%= f.hidden_field :following_id, value: user.id %>
        <%= f.submit 'フォローする', class: 'btn btn-outline-success' %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/profile/edit.html.erb
<h2>プロフィールの変更</h2>
<hr size="10" noshad>
<div class="nav justify-content-end mt-5">
  <%= link_to 'ユーザー登録情報に関する設定', edit_user_registration_path, class: 'btn btn-light' %>
</div>
<%= form_with model: @user, url: profile_update_user_path, local: true do |f| %>
  <div class="mt-5">
    <div class="form-group">
      <%= f.label :name, 'ニックネームの変更' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group mt-5">
      <%= f.label :introduction, '自己紹介の編集' %>
      <%= f.text_area :introduction, class: 'form-control' %>
    </div>

    <div class="mt-5">
      <p>アバターの変更</p>
      <div id="preview">
          <%= image_tag @user.avatar.variant(gravity: :center, resize:"360x360^", crop:"360x360+0+0").processed,
                    class: 'user-avatar-trim-to-circle mt-3', id: 'user_avatar' %>
      </div>
    </div>

    <div class="input-group mt-5">
      <div class="custom-file">
        <%= f.file_field :avatar, class: 'custom-file-input', name: 'user[avatar]' %>
        <%= f.label :avatar, 'ファイル選択...', class: 'custom-file-label', data: {browse: '参照'} %>
      </div>
    </div>

    <div class="nav justify-content-end mt-5">
      <%= f.submit '変更を反映する', class: 'btn btn-primary' %>
    </div>

  </div>
<% end %>

<script>

  $('.custom-file-input').on('change', handleFileSelect);
  function handleFileSelect(evt) {
    // 繰り返し実行時の処理
    $('#preview').remove();
    $(this).parents('.input-group').before('<div id="preview"></div>');

    var file = evt.target.files[0];
    var reader = new FileReader();

    reader.onload = (function(theFile) {
      return function(e) {
        if (theFile.type.match('image.*')) {
          // 画像のプレビューの表示
          var $html = [
            '<div class="d-inline-block mt-3"><img class="user-avatar-trim-to-circle " src="', e.target.result,'" title="', escape(theFile.name), '" /></div>'
            ].join('');
        }
        $('#preview').append($html);
      };
    })(file);
    reader.readAsDataURL(file);

    $(this).next('.custom-file-label').html(+ evt.target.files.length + '個のファイルを選択しました');
  }

</script>

app/views/users/profile/show.html.erb
<div style="height: 12rem">
  <div class="nav justify-content-center">
    <div>
      <%= link_to @user.avatar.variant(resize:"1024x1024^").processed, target: '_blank' do %>
        <%= image_tag @user.avatar.variant(resize: "360x360").processed, class: 'user-avatar-trim-to-circle', id: 'user_avatar', title: @user.avatar.filename %>
        <% if user_signed_in? && @user.id == current_user.id %>
          <div class="nav justify-content-center mt-3">
            <%= link_to 'ユーザー情報の編集', profile_edit_user_path, class: 'btn btn-light'  %>
          </div>
        <% elsif user_signed_in? %>
          <div class="nav justify-content-center mt-3">
            <%= render partial: 'follow_btn', locals: {user: @user} %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="nav justify-content-center mt-5">
  <i class="mr-3"><%= link_to  "フォロー: #{@user.followings.size}", followings_user_path(@user), class: 'text-muted', id: "following-size" %></i>
  <i><%= link_to "フォロワー: #{@user.follower.size}", follower_user_path(@user), class: 'text-muted', id: "follower-size" %></i>
</div>

<div class="nav justify-content-center mt-5">
  <% if @user.introduction %>
    <div style="text-align: center;">
      <p><%= simple_format(@user.introduction) %></p>
    </div>
  <% end %>
</div>

<div class="mt-5">
  <h2><%= @user.name %>の投稿</h2>
  <hr size="20" noshad>
  <div class="card-deck">
    <% @posts.each do |post| %>
      <div class="mr-3 mb-3" style="display: flex; flex-wrap: wrap">
        <div class="card" style="width: 12rem" id="<%= post.user.name + "の投稿" %>">
          <% if post.image.attached? %>
            <%= link_to post_path(post), target: "_blank" do %>
              <%= image_tag post.image.variant(gravity: :center, resize:"480x480^", crop:"480x480+0+0").processed,
                      class: 'card-img-top', style: 'width: 100%; height: auto', alt: post.image.filename %>
            <% end %>
          <% end %>

          <div class="card-body">
            <div id="likes_buttons_<%= post.id %>">
              <%= render partial: 'likes/like', locals: {post: post} %>
            </div>
            <p class="card-text"><small class="text-muted">投稿日時: <%= post.created_at.strftime("%Y-%m-%d %H:%M") %></small></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @posts %>
</div>

<%= render partial: 'shared/create_new_post_btn' %>